### ISSUE TITLE
USB connection pinout error

### ISSUE THREAD

**Issue by aaronbeekay** [BuckeyeCurrent/BeagleBone-CAN-Backpack#10]
An error in TE.lbr caused the DATA+ and DATA- lines on the USB header 1734035-2 to be swapped. This error is reflected in the board.

The board should be updated with the correct part footprint from Component-libraries and the traces should be re-routed.

**Comment by aaronbeekay** [comment]
For the time being, this is being fixed with a wire jumper: 

![cape_rewire](https://cloud.githubusercontent.com/assets/7378316/6658782/eb40bbda-cb4a-11e4-8a68-5e662ceb91af.png)

**Comment by kimconcillado** [comment]
Before:
![image](https://cloud.githubusercontent.com/assets/8769033/6862145/1cbca99e-d41a-11e4-9263-4f0f4bd42bc9.png)
After: 
![image](https://cloud.githubusercontent.com/assets/8769033/6862152/44910794-d41a-11e4-8bdd-a59753635f13.png)

**Comment by kimconcillado** [comment]
Nevermind that screwed up the component. Switched D- and D+ in package for this change:
![image](https://cloud.githubusercontent.com/assets/8769033/6862177/e15fa4ae-d41a-11e4-8273-84d717be98db.png)

**Comment by aaronbeekay** [comment]
@kimconcillado - the library issue was fixed in BuckeyeCurrent/Component-libraries@8c23d857adbadf96802d94fc818086bdd23f7cfa. You shouldn't have to make any more changes to TE.lbr - just make sure you have the latest version from Component-libraries and route accordingly.

**Comment by kimconcillado** [comment]
![screenshot 2015-03-27 08 24 35](https://cloud.githubusercontent.com/assets/8769033/6867692/e582c6ac-d45a-11e4-81cd-35ee05da2792.png)

**Comment by aaronbeekay** [comment]
@kimconcillado Sorry I missed this. If you're pulling from BuckeyeCurrent, you should pull into whatever branch you're currently working from. It looks like that's "Beaglebone_Components", so you should pull there.

**Comment by aaronbeekay** [comment]
Merged in #16.
