### ISSUE TITLE
+12V - +5V power supply doesn't work

### ISSUE THREAD

**Issue by aaronbeekay** [BuckeyeCurrent/BeagleBone-CAN-Backpack#11]
When the board is plugged in, it shorts the +12V input to the +5V rail.

**Comment by aaronbeekay** [comment]
Some behavior observed during testing today:

* The short is not present on a bare PCB.
* The short seems to be through the LMR14206 IC. After the IC is plugged in once, the VIN and SW pins are shorted together by 0.5 – 2 ohms.

I tried replacing the '14206 IC. Before the circuit was powered up, the resistance between VIN and SW was large (over Rbeep). After it was powered up, the rails were shorted again.

I think we should populate another PCB with just the power supply circuit to troubleshoot.

**Comment by kimconcillado** [comment]
CAN Cape #2 power supply circuit was assembled and 12V was put in. It works so the first board must have been an assembly issue.

**Comment by aaronbeekay** [comment]
@kimconcillado Thanks - I will close this out. If we have further issues in the future we can look into improving process controls.
