### ISSUE TITLE
TXCAN and RXCAN signals swapped

### ISSUE THREAD

**Issue by aaronbeekay** [BuckeyeCurrent/BeagleBone-CAN-Backpack#12]
The TXCAN signal (data from BeagleBone to transmit) is connected to pin 4 (RXD) of the CAN transceiver IC8. 

The RXCAN signal (data from CAN bus to BeagleBone) is connected to pin 1 (TXD).

These signals should be connected in the opposite way: RXCAN should go to RXD, and TXCAN should go to TXD.

![image](https://cloud.githubusercontent.com/assets/7378316/6660181/99f6468a-cb6a-11e4-88e6-3a298336c295.png)

**Comment by aaronbeekay** [comment]
We actually had a [discussion about this](https://lists.osu.edu/mailman/private/current-tech/2015-February/001467.html) on current-tech in February. Jenn correctly pointed out that the signals were swapped on the BeagleBone header, and they were fixed.

Unfortunately, the signals were double-swapped -- they were also wrong going into the CAN transceiver. Nobody noticed this in the design review.

**Comment by kimconcillado** [comment]
![image](https://cloud.githubusercontent.com/assets/8769033/6862060/e65ecfe6-d417-11e4-94d2-b0fb85c09714.png)
@aaronbeekay triple swapped? It looks like these are supposed to be fixed as well?

**Comment by aaronbeekay** [comment]
@kimconcillado No, I think that's correct -- the "TXD" line is data coming out of the FT232 (TX) and going into the BB (RX).

**Comment by kimconcillado** [comment]
Resolved.

**Comment by aaronbeekay** [comment]
Merged in #16.
