### ISSUE TITLE
Add LED driver circuit for front panel indicator LEDs

### ISSUE THREAD

**Issue by aaronbeekay** [BuckeyeCurrent/BeagleBone-CAN-Backpack#13]
The BeagleBone needs to drive two indicator LEDs (on the rider display). They should be controlled from GPIO signals on the BeagleBone, and be broken out to connector(s).

**Comment by aaronbeekay** [comment]
According to the [LED indicator datasheet](http://datasheet.octopart.com/19240254-CML-Innovative-Technologies-datasheet-10674112.pdf), the LEDs draw 20 mA nominal, 40 mA if both are turned on (but they need separate channels).

@crs0002, @Victorb101 -- it looks like the currently selected LED is a bicolor LED. Do you need to be able to control each color (two channels per indicator), or just on/off (one channel per indicator)?

**Comment by aaronbeekay** [comment]
Regardless, because the LEDs are to be driven from +12V, the "normal" LED driver circuit we use (with the SN65LVC2G07) won't work, because it doesn't like 12V on its pins.

We can use the LED switching circuit from the BIM, using the [FDV301N](https://www.fairchildsemi.com/datasheets/FD/FDV301N.pdf) as a low-side switch. The FDV301N is 25V rated, and we have plenty of them in stock.

I will try to sketch this out tomorrow, it shouldn't be too hard.

@sharrington93 - do you know which pins you want to use to control the indicator LEDs?

**Comment by sharrington93** [comment]
@aaronbeekay how many pins total? 4?

**Comment by aaronbeekay** [comment]
@sharrington93 Uh, sure, call it 4 for now, just in case.

**Comment by sharrington93** [comment]
@aaronbeekay 45, 23, 47, 27

**Comment by aaronbeekay** [comment]
Here's my proposed LED drive circuit (per-LED):

![image](https://cloud.githubusercontent.com/assets/7378316/6887823/c5e0e1a0-d61f-11e4-8465-ad97f622bb2f.png)

We haven't quite decided what the connectors will end up being, though.

**Comment by aaronbeekay** [comment]
@kimconcillado - I've added the component for Q2 (BSS84) to Fairchild Semiconductor.lbr. You should be able to pull it from BuckeyeCurrent/Component-libraries at your convenience.

It's up to you, but I would use a 3pos Dura-Clik connector for each LED. If you would like to do this, the appropriate vertical header is in Molex.lbr.

**Comment by aaronbeekay** [comment]
Merged in #16.
