### ISSUE TITLE
Add +12V_CONST / standby mode functionality

### ISSUE THREAD

**Issue by aaronbeekay** [BuckeyeCurrent/BeagleBone-CAN-Backpack#14]
To comply with the latest plan for the Rider Display power functionality:

* The BeagleBone should be powered from +12V_CONST when +12V_MAIN is unavailable.
* The BeagleBone should have the power state of +12V_MAIN provided on some pin, so that it can detect when power is lost or restored.

**Comment by aaronbeekay** [comment]
@sharrington93 - this is going to block until your team figures out what pin you want the sleep/wake interrupt on.

**Comment by sharrington93** [comment]
@aaronbeekay @kimconcillado let's do GPIO_66 since it looks like there's more room near that pin

**Comment by aaronbeekay** [comment]
@kimconcillado - here's my proposed revisions to the BB power circuit.

* The BeagleBone +5V supply is powered by +12V_CONST now, not +12V_MAIN.
* Two new connectors are added:
  * One connector, labeled "Power connector (input)" here, provides +12V_MAIN to the Rider Display, and +12V_CONST to the BeagleBone. I think a Micro-Fit 4pos connector is appropriate here.
  * The other connector, labeled "LCD Power" here, provides the power supply to the Rider Display. This could be a Dura-Clik 2pos or Micro-Fit 2pos (Dura-Clik 2pos will be smaller).

![image](https://cloud.githubusercontent.com/assets/7378316/6887494/e1fbcfb2-d615-11e4-9cea-d964ea38789e.png)

**Comment by sharrington93** [comment]
@aaronbeekay @kimconcillado I may need two GPIO pins to make this work. One that signals that power has been lost and another saying it's restored.

**Comment by aaronbeekay** [comment]
@sharrington93 - how are those different?

As drawn, you should get a falling edge on GPIO_66 when power is lost, and a rising edge when power is restored. The pin will be HIGH when power is on, and LOW when it is off.

**Comment by sharrington93** [comment]
@aaronbeekay I may not be able to trigger an interrupt on both a rising and falling edge.

**Comment by aaronbeekay** [comment]
@sharrington93 Really? That sounds unusual.

In that case, would it work to just bring the WAKE signal to two separate pins?

**Comment by sharrington93** [comment]
@aaronbeekay What would putting the same WAKE signal into two different pins do?

**Comment by aaronbeekay** [comment]
@sharrington93, @kimconcillado - per discussion in #16, OK if we move the WAKE signal to pins P8-14 and P8-17 (GPIO0_26 and GPIO0_27)?

**Comment by aaronbeekay** [comment]
Merged in #16.
