### ISSUE TITLE
Add X-346, connector supplying +12V power to the Rider Display LCD driver panel

### ISSUE THREAD

**Issue by aaronbeekay** [BuckeyeCurrent/BeagleBone-CAN-Backpack#15]
X-346 should have two signals: +12V_MAIN and GND. It should be able to support ~500 mA of current on these pins.

X-346 is described on the [Front Enclosure drawing](https://github.com/BuckeyeCurrent/Vehicle-wiring-diagrams/blob/master/Front%20Enclosure/Front%20Enclosure%20Drawing.pdf).

**Comment by aaronbeekay** [comment]
@kimconcillado - You can pick what kind of connector you want to use here. Victor suggested a 2pos Micro-Fit. I suggest using a 2pos Dura-Clik header - they are smaller, less expensive, and we have the tooling for them.

I've added the 2pos Dura-Clik headers in vertical and horizontal orientations to Molex.lbr, in [this PR](https://github.com/BuckeyeCurrent/Component-libraries/pull/72). They should be available for you to use now if you'd like to.

**Comment by kimconcillado** [comment]
@aaronbeekay you added the components to Molex, but the devices don't have a package and/or symbol. Did you want me to make them or did I not pull the most recent components library?

**Comment by aaronbeekay** [comment]
Merged in #16.
