### ISSUE TITLE
No CAN communication on v2.3 board

### ISSUE THREAD

**Issue by aaronbeekay** [BuckeyeCurrent/BeagleBone-CAN-Backpack#19]
@sharrington93 reports that CAN communication doesn't work on the BeagleBone test:

### Procedure
1. Plug CAN Cape into Beaglebone Black
2. Enabled CAN on the Beaglebone.
3. Connected Kvaser to the CAN cape and Kvaser to computer.
4. Sent CAN data from computer to CAN cape.

### Expected Behavior
Nice data incoming on the Beaglebone Black

### Observations
No sign of CAN data on Beaglebone Black.
Error frames on the computer side.

### Notes
I plugged in the old CAN cape from RW-2x afterwards and followed the same procedure. I saw CAN on the Beaglebone Black

**Comment by kimconcillado** [comment]
RXCAN and TXCAN were not routed - RXCAN is now routed with scarlet/gray wire and TXCAN is now routed with blue/black wire

**Comment by aaronbeekay** [comment]
OK, sounds like the lines need to be routed. I will take some of the blame here for not catching these issues in design review.

For posterity, one big part of the issue was that the "Unrouted" layer was turned off in the file submitted -- I didn't notice this and didn't pay attention to the output of the Ratsnest command, so I didn't realize that there were traces unrouted still.

**Comment by aaronbeekay** [comment]
This issue is resolved in bb4a220627aac7900673e7581fbcf682cb0472ab

**Comment by aaronbeekay** [comment]
Resolved in #22.
