### ISSUE TITLE
LEDs tied into HDMI Communication Pins

### ISSUE THREAD

**Issue by sharrington93** [BuckeyeCurrent/BeagleBone-CAN-Backpack#20]
@kimconcillado 
We tied the LEDs into the HDMI communication pins. I finally realize the "LCD Data" pins are really "HDMI" pins in a sense. The HDMI pins get tied up by what's called a "virtual cape". Basically when you enable HDMI, it causes these pins to become in use (even if you aren't using an actual cape). So I don't have the ability to change the colors of the LEDs.

I'll work on trying to find pins that will actually work

**Comment by aaronbeekay** [comment]
@sharrington93 Do you have any picks for which pins the LEDs should be controlled by?

**Comment by sharrington93** [comment]
@kimconcillado @aaronbeekay 

I've just tested these pins directly on the Beaglebone and made sure I can switch their state:
Pin 67,68,44,26

**Comment by kimconcillado** [comment]
I'm getting the pinout information from http://www.farnell.com/datasheets/1685587.pdf and I'm having trouble locating pins 26,44, 67, and 68. P8 pinout is page 49 and P9 is page 51 and I can't find some of the numbers as pin numbers or GPIO labels

**Comment by kimconcillado** [comment]
nvm figured it out they're all on P8. I googled it

**Comment by aaronbeekay** [comment]
Resolved in #22.
