### ISSUE TITLE
Serial header misaligned

### ISSUE THREAD

**Issue by aaronbeekay** [BuckeyeCurrent/BeagleBone-CAN-Backpack#9]
The serial port header that mates with the BeagleBone is offset by 3-4 pins.

It should be corrected so that it mates with the BeagleBone correctly.

**Comment by aaronbeekay** [comment]
For the time being, @Victorb101 has hacked a wired connector onto these pins, so that the serial port functionality can be tested.

**Comment by kimconcillado** [comment]
According to the datasheet (page 55 for picture) http://www.farnell.com/datasheets/1685587.pdf it looks like its off by a single pin width. 
![image](https://cloud.githubusercontent.com/assets/8769033/6862789/6ba197de-d41c-11e4-9c37-59429cff9d53.png)
I am planning to move it one pin width to the left. Is this correct?

**Comment by aaronbeekay** [comment]
Hey @Victorb101 @sharrington93 - can one of you confirm that the serial header on the CAN Cape is off by 0.1" in the X direction (as Kim describes above)?

**Comment by Victorb101** [comment]
@kimconcillado @aaronbeekay @sharrington93 

A quick look at the datasheet shows that no, the serial header is off by 2 pins.  It should be moved 0.2" left in the X direction.

**Comment by kimconcillado** [comment]
resolved

**Comment by aaronbeekay** [comment]
Merged in #16.
